### ISSUE TITLE
Wondering about "can_compress" in decompress proc,

### ISSUE THREAD

**Issue by oderwat** [dfdeshom/nimsnappy#1]
I just read the code and wondered about the variable name in the line [109](https://github.com/dfdeshom/nimsnappy/blob/master/snappy.nim#L109) shouldn't that be "can_uncompress" or "is_compressed"? Nothing important just made me think and the error message wording is strange too in that context.

**Comment by dfdeshom** [comment]
You are correct. It should be `can_uncompress` and the error message be something like `malformed compressed input` (or something better). I can get to it later, but feel free to submit a PR (even better). Thanks!

**Comment by dfdeshom** [comment]
closed here: https://github.com/dfdeshom/nimsnappy/commit/ab6bfa4065dbec9137350994740f359d13b0b01c . Thanks!
